### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by bobbbob** [fluffymadness/ATMega32U4-Switch-Fightstick#2]
I'm getting this error while trying to compile the sketch. Any help would be much appreciated.

Arduino: 1.8.10 (Mac OS X), Board: "Arduino/Genuino Micro"

In file included from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBTask.h:47:0,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/USB.h:386,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:11,
                 from /Users/userName/Documents/Arduino/switchFightstick/switchFightstick.ino:2:
/Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBController.h:113:0: warning: "EP_TYPE_CONTROL" redefined
   #define EP_TYPE_CONTROL                    0x00
 
In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:233:0,
                 from sketch/switchFightstick.ino.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBAPI.h:50:0: note: this is the location of the previous definition
 #define EP_TYPE_CONTROL    (0x00)
 
In file included from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/../Device.h:55:0,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.h:67,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBController.h:150,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBTask.h:47,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/USB.h:386,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:11,
                 from /Users/userName/Documents/Arduino/switchFightstick/switchFightstick.ino:2:
/Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/../StdDescriptors.h:79:0: warning: "USB_CONFIG_POWER_MA" redefined
    #define USB_CONFIG_POWER_MA(mA)           ((mA) >> 1)
 
In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBAPI.h:44:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:233,
                 from sketch/switchFightstick.ino.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.h:99:0: note: this is the location of the previous definition
 #define USB_CONFIG_POWER_MA(mA)                ((mA)/2)
 
In file included from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBTask.h:47:0,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/USB.h:386,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:11,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.h:4,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.cpp:1:
/Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBController.h:113:0: warning: "EP_TYPE_CONTROL" redefined
   #define EP_TYPE_CONTROL                    0x00
 
In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:233:0,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:8,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.h:4,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBAPI.h:50:0: note: this is the location of the previous definition
 #define EP_TYPE_CONTROL    (0x00)
 
In file included from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/../Device.h:55:0,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.h:67,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBController.h:150,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/USBTask.h:47,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/USB.h:386,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:11,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.h:4,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.cpp:1:
/Users/userName/Documents/Arduino/libraries/LUFA/LUFA/LUFA/Drivers/USB/Core/AVR8/../StdDescriptors.h:79:0: warning: "USB_CONFIG_POWER_MA" redefined
    #define USB_CONFIG_POWER_MA(mA)           ((mA) >> 1)
 
In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBAPI.h:44:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:233,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFA.h:8,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.h:4,
                 from /Users/userName/Documents/Arduino/libraries/LUFA/LUFACDCSerial.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.h:99:0: note: this is the location of the previous definition
 #define USB_CONFIG_POWER_MA(mA)                ((mA)/2)
 
USBCore.cpp.o (symbol from plugin): In function `RxLEDPulse':
(.text+0x0): multiple definition of `__vector_10'
sketch/LUFA.c.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Multiple libraries were found for "LUFA.h"
 Used: /Users/userName/Documents/Arduino/libraries/LUFA
Multiple libraries were found for "Bounce2.h"
 Used: /Users/userName/Documents/Arduino/libraries/Bounce2
exit status 1
Error compiling for board Arduino/Genuino Micro.

Edit:
My apologies for the support like post. I now believe this issue stems from being run on a Mac, the python script to install LUFA didn’t have access to the Arduino IDE files to edit. I will attempt to edit them manually.

**Comment by JacMac** [comment]
hello, does it compile now? I am running into an identical error.

**Comment by dscythegeo** [comment]
Was wondering anyone manage to build this? Or can anyone upload the joystick.hex file somewhere? Maybe the author can code a makefile version? I can build bootsector/XInputPadMicro just fine in git bash and i have setup avr tool chain and all that jazz.

But this one i ran into an identical error as the first post.

**Comment by JacMac** [comment]
The problem looks to be the LUFA library conflicting with the more up to date ide, I used the 1.8.2 and it worked out

**Comment by dscythegeo** [comment]
Alright i'll give it another go with the 1.8.2 IDE.

**Comment by dscythegeo** [comment]
I got a bit further but still ends in an error when it starts to link everything together:

Archiving built core (caching) in: C:\Users\USER\AppData\Local\Temp\arduino_cache_351752\core\core_arduino_avr_micro_9e600a72e77171b37a24b5e0b5773245.a
Linking everything together...
"C:\Users\USER\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega32u4  -o "C:\Users\USER\AppData\Local\Temp\arduino_build_796200/main.ino.elf" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\sketch\Descriptors.c.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\sketch\Joystick.c.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\sketch\LUFA.c.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\sketch\main.ino.cpp.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\libraries\LUFA\LUFACDCSerial.cpp.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200\libraries\Bounce2\Bounce2.cpp.o" "C:\Users\USER\AppData\Local\Temp\arduino_build_796200/core\core.a" "-LC:\Users\USER\AppData\Local\Temp\arduino_build_796200" -lm
USBCore.cpp.o (symbol from plugin): In function `RxLEDPulse':

(.text+0x0): multiple definition of `__vector_10'

C:\Users\USER\AppData\Local\Temp\arduino_build_796200\sketch\LUFA.c.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Using library LUFA in folder: C:\Arduino\libraries\LUFA (legacy)
Using library Bounce2 at version 2.52 in folder: C:\Arduino\libraries\Bounce2 
exit status 1
Error compiling for board Arduino Micro.

So am I doing something wrong or something else entirely?

**Comment by JacMac** [comment]
Have you tried clearing the Arduino local data?  Does it say Arduino 1.8.10 in the top right corner?

**Comment by dscythegeo** [comment]
how do I clear the arduino local data? I'm using arduino 1.8.2. I'm on windows 10 os by the way.

**Comment by dscythegeo** [comment]
Anyway i got the arduino IDE to build the code successfully. I deleted the arduino folder in C:\Users\USER\AppData\Local\Temp\ and i used an older LUFA libraries from http://www.fourwalledcubicle.com/LUFA.php version 170418.

Replacing the LUFA folder in the <arduino_install_path>\libraries\

Is there a pinout diagram sort of like this PNG ?https://raw.githubusercontent.com/bootsector/XInputPadMicro/master/docs/XInputPadMicroPinout.png

**Comment by Element2424** [comment]
I think that I am having the same problem, only using the  older LUFA libraries didn't help, is there anything else that you did? or maybe that I am missing 



USBCore.cpp.o (symbol from plugin): In function `RxLEDPulse':

(.text+0x0): multiple definition of `__vector_10'

C:\Users\AppData\Local\Temp\arduino_build_152936\sketch\LUFA.c.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "LUFA.h"
 Used: C:\Users\Documents\Arduino\libraries\LUFA
Multiple libraries were found for "Bounce2.h"
 Used: C:\Users\Documents\Arduino\libraries\Bounce2
Using library LUFA in folder: C:\Users\Documents\Arduino\libraries\LUFA (legacy)
Using library Bounce2 at version 2.52 in folder: C:\Users\Documents\Arduino\libraries\Bounce2 
exit status 1
Error compiling for board Arduino Leonardo.

**Comment by FeralAI** [comment]
For anyone looking to resolve this issue - "activating" the LUFA library updates some AVR lib files in the Arduino IDE `hardware\arduino\avr\cores\arduino` folder, however when compiling it's pulling dependencies from `%USERPROFILE%\AppData\Local\Arduino15\packages\arduino\hardware\avr\<version>\cores\arduino`.  As of AVR 1.8.3 the modified files are identical, so you can copy the following files from the IDE path to the AppData path after running the LUFA activation:

- Arduino.h
- main.cpp
- CDC.cpp
- PluggableUSB.cpp
- PluggableUSB.h
- USBAPI.h
- USBCore.cpp
- USBCore.h
- USBDesc.h

If you want to manually make the changes you can follow [the manual activate directions](https://github.com/Palatis/Arduino-Lufa/blob/master/docs/manual_installation.md), and update the files in the versioned folder in AppData instead of the IDE `hardware` folder.

**Comment by bobbbob** [comment]
For anyone still having trouble with this I have found CrazyRedMachine’s new method of LUFA installation to be ridiculously easy.

You can find his fork here
`https://github.com/CrazyRedMachine/Arduino-Lufa/tree/new-workflow`

However as this has not been pushed to the main LUFA you will need to use this address for the board lib instead of the one provided in step 2.
`https://github.com/CrazyRedMachine/Arduino-Lufa/raw/library/custom_boards/package_arduino-lufa_index.json`
